### ISSUE TITLE
How to use git

### ISSUE THREAD

**Issue by deletescape** [aospstudio/Oreo_Launcher_Go#1]
Git is meant to be used to directly store the sources in it. It is not a good idea to zip up your source and upload it like that. You directly develop inside of a git repository (any Android Studio project is automatically a git repo) and then you can push this to github. This makes contributing a lot easier, and is also easier for you to manage.

If you need a small introduction to git, here are some simple guides to git: https://guides.github.com/

**Comment by aospstudio** [comment]
Hi, I do not have a worker with knowledge on GitHub yet, can you help us?

8 Mar 2018 Per 09:47 tarihinde Till Kottmann <notifications@github.com>
şunu yazdı:

**Comment by deletescape** [comment]
I would definitely try to help you, but I have very limited time available right now, so all I can do is link you to guides like the one I posted above

**Comment by aospstudio** [comment]
Hello, the source codes of Oreo Launcher and Oreo Launcher Go are normally published in GitHub. Thank you for your attention..
